name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Check secrets
        run: |
          if [ -n "${{ secrets.VITE_SUPABASE_URL }}" ]; then
            echo "Supabase URL is set"
          else
            echo "Supabase URL is NOT set"
          fi
          if [ -n "${{ secrets.VITE_SUPABASE_ANON_KEY }}" ]; then
            echo "Supabase Key is set"
          else
            echo "Supabase Key is NOT set"
          fi
          if [ -n "${{ secrets.VITE_APP_API_URL }}" ]; then
            echo "API URL is set"
          else
            echo "API URL is NOT set"
          fi

      - name: Create env file
        run: |
          touch .env
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
          echo "VITE_APP_API_URL=${{ secrets.VITE_APP_API_URL }}" >> .env
          echo "Content of .env file:"
          cat .env

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
